# Fonc


In [59]:
# créons un vecteur de données numérique en objet array
import numpy as np
Matrice = np.array(range(10))

In [65]:
# créons une fonction qui standardise un vecteur (type 1darray) : centrer et réduire (soustraire la moyenne et diviser par l'écart type)
# x doit etreu un np.array car on applique dessus np.mean ...
def standardisation(x): 
        x-=np.mean(x) # the -= means can be read as x = x- np.mean(x)
        x/=np.std(x)
        return x

In [60]:
# appliquons la fonction standardisation, attention aux types des données
Matrice.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
standardisation(Matrice.astype(float))

array([-1.5666989 , -1.21854359, -0.87038828, -0.52223297, -0.17407766,
        0.17407766,  0.52223297,  0.87038828,  1.21854359,  1.5666989 ])

In [64]:
# si on applique la fonction sur un array non float il y a un erreur

standardisation(Matrice)

TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [66]:
# Introduire une gestion d'exception dans la fonction => try except
def standardisation(x): 
    try:        
        x-=np.mean(x) # the -= means can be read as x = x- np.mean(x)
        x/=np.std(x)
        return x
    except TypeError:
        print("le type des données n'est pas conforme (float attendu)")

In [67]:
standardisation(Matrice)

le type des données n'est pas float


In [75]:
# si matrice2 n'est pas un array mais un tuple
# cela marche car np.mean fonctionne sur une liste de val numériques
matrice2=(1,2,3,4)
print(type(matrice2))
standardisation(matrice2)
print(np.mean(matrice2))

<class 'tuple'>
2.5


## Lambda Function

In [77]:
# appliquons une lambda fonction pour mettre au carré les valeurs du vecteur numérique
# utilise la lambda func pour à tout x renvoyer f(x)=x²
# map applique une fonction à un iterable, ici le tuple numbers
map(lambda x :x**2,Matrice)

In [93]:
# fonction qui test esi un element vaut 1
result= list(map(lambda x: x==1.00, Matrice))
print(result)
result.count(False)

[False, True, False, False, False, False, False, False, False, False]


9

In [ ]:
#python ne sait pas représenter l'instance donc il faut la transformer
list(map(lambda x :x**2,Matrice))

In [ ]:
# Créer une fonction qui retourne l'aire d'un triangle et l'appliquer pour un triangle de base 2 et de hauteur 3
f = lambda base, hauteur : (base*hauteur)/2
f(base = 2,hauteur = 3)

## COMPLEMENT MODULE DE FONCTIONS

In [14]:
# on déclare un repertoire supplémentaire 
# où python peut aller chercher des définitions de modules
import sys
sys.path.append("C:\\Users\\dgr\\Documents\\Formations\SCU Python\\NEW\modules")
sys.path


['',
 'C:\\Users\\dgr\\Documents\\Formations\\SCU Python\\NEW\\Jupyter',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\python37.zip',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\DLLs',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\chardet-3.0.4-py3.7.egg',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\docloud-1.0.257-py3.7.egg',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\dgr\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\dgr\\.ipython',
 'C

In [16]:
# importation d'une fonction stockée en module
from standardisation import standardisation

In [17]:

# test de la fonction sur une dataframe
import pandas as pd
iris = pd.read_json("iris.json")

# axis=0 on raisonne par col, on prend toutes les lignes de chaq col

# utilisation de la fonction , en entrée on attend 1 vecteur
iris_norm_petal_length= standardisation(iris['petalLength'])


In [18]:
iris_norm_petal_length.mean(axis=0)

-1.6890192947964048e-15

In [19]:
# ma fonction ne marche sur plusieurs vecteurs, donc il faut que j'applique col apres col la fonction avec apply
iris_norm = iris[['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth']].apply(standardisation,axis=0)

In [20]:
# par défaut axis=0, on voit que la moy =0
iris_norm.mean(axis=0)
iris_norm.mean()

petalLength   -1.450691e-16
petalWidth    -1.442550e-15
sepalLength   -1.652382e-15
sepalWidth    -1.862399e-15
dtype: float64

## BONUS SERIALISATION PICKLE

In [4]:
import pickle

In [ ]:
# L'étape suivante lit un fichier, effectue des manipulations et crée une datafram
# Comment sauvegarder l'objet pour éviter de repartir à zéro

In [2]:
import pandas as pd
import os # commandes systèmes pour definir le rép de travail
#repertoire = "C:\\Users\\dgr\\Documents\\Formations\\SCU Python\\NEW\\data"
os.chdir("D:/Users/pcformation/Desktop/formationPy/data")
#os.getcwd()

# pandas permet de lire un json et de créer une table
iris = pd.read_json("iris.json")
iris.columns # index des col
# on renomme les colonnes
iris.columns = ['longueurPetale', 'largeurPetale', 'longueurSepale', 'largeurSepale', 'espece']

# structure
#iris.info()

# on change le type de l'espece
iris.espece = iris.espece.astype('category')
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
longueurPetale    150 non-null float64
largeurPetale     150 non-null float64
longueurSepale    150 non-null float64
largeurSepale     150 non-null float64
espece            150 non-null category
dtypes: category(1), float64(4)
memory usage: 5.0 KB


In [5]:
# Sauvegarder IRIS
file=open("monfichier_surmondisque.df","wb")
pickle.dump(iris,file)
file.close()

In [6]:
import os
os.getcwd()

del iris



In [7]:
iris.dtypes

NameError: name 'iris' is not defined

In [12]:

file=open("monfichier_surmondisque.df","rb")
iris=pickle.load(file)
file.close()

In [13]:
iris.dtypes

longueurPetale     float64
largeurPetale      float64
longueurSepale     float64
largeurSepale      float64
espece            category
dtype: object

## GESTION DES TIRAGES ALEATOIRES
La graine doit être exécuté avant chaque utilisation d'une fonction aléatoire

In [ ]:
#initialiser la graine pour l'aléa
SEED=2018
np.random.seed(SEED)
# on lance une fois
print(np.random.uniform(0,1,3))
# [0.88234931 0.10432774 0.90700933]
# la deuxieme fois, cela change car la seed n'est plus prise en compte
print(np.random.uniform(0,1,3))
#[0.3063989  0.44640887 0.58998539]
# on refixe
np.random.seed(SEED)
print(np.random.uniform(0,1,3))
#[0.88234931 0.10432774 0.90700933]

# Tirage d'individus
s = np.random.normal(-3,3,1000)


In [ ]:
## PERCENTILES


In [ ]:
import numpy as np
x=np.random.rand(100)

In [ ]:
deciles=range(0,101,10)
print(deciles)


In [ ]:
np.nanpercentile(x,deciles)

In [ ]:
deciles=np.arange(0,100,100/3)
print(deciles)

In [ ]:
np.nanpercentile(x,deciles)

In [ ]:
y=np.random.rand(100)

np.corrcoef(x,y)

##  Les variables sont des pointeurs

In [23]:
# deux variables différentes qui pointent sur la meme donnée
var1 = 5
var2 = 5
var3 = 5.0
var4 =var1

In [24]:
# Affiche l'adresse mémoire de localisation de la donnée
# python variables sont des pointeurs
print(hex(id(var1)))
print(hex(id(var2)))
print(hex(id(var3)))
print(hex(id(var4)))

0x7ffc31ecef80
0x7ffc31ecef80
0x2f5d306b2b8
0x7ffc31ecef80


In [25]:
# si on modifie la valeur, l'emplacement change

In [27]:
var1 = var1**2

In [28]:
print(hex(id(var1)))
print(hex(id(var2)))
print(hex(id(var3)))
print(hex(id(var4)))

0x2f5d2f467d0
0x7ffc31ecef80
0x2f5d306b2b8
0x7ffc31ecef80


In [1]:
import psutil

In [2]:
print(psutil.virtual_memory())

svmem(total=8415711232, available=4119973888, percent=51.0, used=4295737344, free=4119973888)


In [5]:
# Big vecteur numérique de 500 M 
import numpy as np
x=np.random.rand(500000000)

In [6]:
print(psutil.virtual_memory())

svmem(total=8415711232, available=56209408, percent=99.3, used=8359501824, free=56209408)


In [7]:
del x

In [8]:
print(psutil.virtual_memory())

svmem(total=8415711232, available=6080245760, percent=27.8, used=2335465472, free=6080245760)
